title: Zlatko Lakisic
description: Engineering Leader · Technical Strategy & Customer-Centric Solutions
logo: /assets/profile.jpg
url: https://zlatko-lakisic.github.io
baseurl: /zlatko-lakisic
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

relative_links:
  enabled: true
  collections: true

show_downloads: false

github_username: zlatko-lakisic
google_analytics: G-0R57S4CBRC

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - portfolio.code-workspace
  - README.profile.md
  - README.md
